version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      # - my-strapi-project_strapi-data:/var/lib/postgresql/data/  # Added volume mount
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 # for M1 chip compatibility
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
      # - my-strapi-project_strapi-data:/var/lib/postgresql/data/  # Added volume mount
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:
  # my-strapi-project_strapi-data:  # Added named volume

networks:
  strapi:
    name: Strapi
    driver: bridge
